stages:
  - build-and-test

default:
  image: docker.grammatech.com/rewriting/gtirb-ghidra-plugin
  tags: ["shared"]

build-and-test:
  stage: build-and-test
  script:
  - echo "Building plugin..."
  - apt-get update -y && apt-get install -y pip wget unzip && pip install ddisasm
  # Build the GTIRB Java API and plugin using gtirb_java_build.sh
  - cd ${CI_PROJECT_DIR}
  - ./scripts/gtirb_java_build.sh
  # Build the plugin and install in Ghidra
  - cd ${CI_PROJECT_DIR}/Gtirb
  - ./install_plugin.sh
  # Run test scripts using plugin in headless mode
  - cd ${CI_PROJECT_DIR}/tests
  - ./test-import hello_x64.elf
  - ./test-import hello_ia32.elf
  #- if [ -n "$INTERNAL_APT_REPO" ]; then ./test-import hello_arm.elf; fi
  #- if [ -n "$INTERNAL_APT_REPO" ]; then ./test-import hello_ppc.elf; fi
